"""initial schema

Revision ID: 84f67a745804
Revises: 
Create Date: 2026-06-03 00:53:11.219399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84f67a745804'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('conversations', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('property_images', sa.Column('is_cover', sa.Integer(), nullable=True))
    op.alter_column('property_images', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_images', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('property_images', 'is_cover')
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('messages', 'created_at')
    op.alter_column('listings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conversations', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
